### ISSUE TITLE
TypeError on Traffic Policy A records

### ISSUE THREAD

**Issue by yoshiakikuida** [gtaylor/python-route53#17]
Hi,

I'm having trouble listing all my records in Route53 because there's an A record associated with a traffic policy that causes a type error to be thrown in list_resource_record_sets_by_zone_id.py for method parse_rrset. The issue is that once it throws an exception from the traffic policy record, the generator stops and I can't get any of the records after that record.

My current workaround is to catch the TypeError from `subclass = RRSetSubclass(**kwargs)` and return None (just ignoring it).

I was wondering if there were any plans to add traffic policy support?

Thanks!

**Comment by gtaylor** [comment]
Hello,

I'm not currently actively using python-route53. I'd be glad to talk about what a PR might look like if someone is interested in tackling it, but have no plans to add such a thing myself right now.

**Comment by yoshiakikuida** [comment]
I'm ok with the workaround for now, thanks for your quick response
